# urls of Lotus.vn
get_all_followers = 'https://webpub.lotuscdn.vn/api/webkinghub/kinghub-user/view-follow-detail'
get_all_fans = 'https://webpub.lotuscdn.vn/api/webkinghub/kinghub-user/view-follower-detail'
get_all_posts = 'https://webpub.lotuscdn.vn/api/webkinghub/kinghub-personal/posts'
get_all_groups_joined = 'https://webpub.lotuscdn.vn/api/webkinghub/kinghub-group/member/get-all-group'
get_all_activities = 'https://webpub.lotuscdn.vn/api/webkinghub/kinghub-user-activities'
get_detail_user_info = 'https://webpub.lotuscdn.vn/api/webkinghub/kinghub-user/get-user-profile'
get_token = 'https://webpub.lotuscdn.vn/api/social/token'
get_new_token = 'https://lotus.vn/w/a/gtk'
get_reactions_of_post = 'https://lotus.vn/w/api/ProfileToken/get-post-react-detail'
